### ISSUE TITLE
Add option to size the figure

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/ProfileVega.jl#4]
Right now the figure is always 800x400. We should probably somehow add an option to adjust the size of it.

**Comment by Arkoniak** [comment]
This would be nice feature to implement, but wouldn't it be more convenient to rethink approach?

As I can see it, currently usage will be something like that
```
Profile.clear()
@profile profile_test(10);

ProfileVega.view(width = 1000, height = 600)
```
There are three problems with this approach
1. You'll be forced to enter `width` and `height` each time you want to generate new profile picture, which is tedious
2. You can't use `@profview` macros because it will always fall to default.
3. `kwargs` arguments which should manage plotting are interleaving with `FlameGraph` options

May be it is better to implement interface like this
```
p = VegaProfiler(width = 1200, height = 600)

Profile.clear()
view(p)

# or

@profview p profile_test(10)
```

**Comment by davidanthoff** [comment]
Maybe a combination of global parameters and keyword args? For example:
```julia
ProfileVega.set_default_size(800, 600)
```
and then still the option to have
```julia
view(width=200, height=300)
@profview profile_test(10) width=200 height=300
```
to adjust things for individual invocations?

There is also https://vega.github.io/vega-lite/docs/size.html#specifying-responsive-width-and-height, but I don't think that will work for us because we probably need to really control the height of the plot...
